{
  "file": "data/example.py",
  "cyclomatic_complexity": [
    "F 1:0->3 hello - 2"
  ],
  "maintainability_index": 100.0,
  "raw_metrics": {
    "loc": 5,
    "lloc": 4,
    "sloc": 4,
    "comments": 0,
    "multi": 0,
    "blank": 1,
    "single_comments": 0
  },
  "pylint": "'pylint' is not recognized as an internal or external command,\noperable program or batch file.",
  "llm_feedback": "Gemini API error: 400 - {\n  \"error\": {\n    \"code\": 400,\n    \"message\": \"API key not valid. Please pass a valid API key.\",\n    \"status\": \"INVALID_ARGUMENT\",\n    \"details\": [\n      {\n        \"@type\": \"type.googleapis.com/google.rpc.ErrorInfo\",\n        \"reason\": \"API_KEY_INVALID\",\n        \"domain\": \"googleapis.com\",\n        \"metadata\": {\n          \"service\": \"generativelanguage.googleapis.com\"\n        }\n      },\n      {\n        \"@type\": \"type.googleapis.com/google.rpc.LocalizedMessage\",\n        \"locale\": \"en-US\",\n        \"message\": \"API key not valid. Please pass a valid API key.\"\n      }\n    ]\n  }\n}\n",
  "dev_score": 97
}